name: Build and publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout repository

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Assemble
      run: ./gradlew assemble || ./gradlew assemble || ./gradlew assemble
      env:
        GITHUB_BUILD: 1

    - name: Build with Gradle
      run: ./gradlew build -S
      env:
        GITHUB_BUILD: 1
